name: Check msoledbsql.dll Version on Windows
on:
  workflow_dispatch:

jobs:
  check-msoledbsql-version:
    strategy:
      matrix:
        runner: [windows-2022, windows-latest]
    runs-on: ${{ matrix.runner }}
    outputs:
      dll_version: ${{ steps.get_version.outputs.dll_version }}
      python_version: ${{ steps.get_python_version.outputs.python_version }}
      node_version: ${{ steps.get_node_version.outputs.node_version }}
    steps:
      - name: Get default Python version
        id: get_python_version
        run: |
          $pyver = python --version 2>&1
          echo "python_version=$pyver" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Get default Node.js version
        id: get_node_version
        run: |
          $nodever = node --version 2>&1
          echo "node_version=$nodever" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      - name: Get msoledbsql.dll Version
        id: get_version
        run: |
          $dllPath = 'C:\Windows\SysWOW64\msoledbsql.dll'
          if (Test-Path $dllPath) {
            $version = (Get-Item $dllPath).VersionInfo.FileVersion
            echo "msoledbsql.dll version: $version"
            echo "dll_version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            echo "msoledbsql.dll not found at $dllPath."
            echo "dll_version=Not found" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

  summary-report:
    needs: check-msoledbsql-version
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Write DLL and Runtime Versions Summary
        run: |
          echo "## Windows Runner Environment Report" >> $GITHUB_STEP_SUMMARY
          echo "| Runner         | msoledbsql.dll Version | Python Version         | Node.js Version     |" >> $GITHUB_STEP_SUMMARY
          echo "|---------------|-----------------------|------------------------|---------------------|" >> $GITHUB_STEP_SUMMARY
          echo "| windows-2022  | ${{ needs.check-msoledbsql-version.outputs.dll_version[0] }} | ${{ needs.check-msoledbsql-version.outputs.python_version[0] }} | ${{ needs.check-msoledbsql-version.outputs.node_version[0] }} |" >> $GITHUB_STEP_SUMMARY
          echo "| windows-latest| ${{ needs.check-msoledbsql-version.outputs.dll_version[1] }} | ${{ needs.check-msoledbsql-version.outputs.python_version[1] }} | ${{ needs.check-msoledbsql-version.outputs.node_version[1] }} |" >> $GITHUB_STEP_SUMMARY
