name: Check msoledbsql.dll Version on Windows
on:
  workflow_dispatch:

jobs:
  check-msoledbsql-version:
    runs-on: windows-latest
    steps:
      - name: Get msoledbsql.dll Version
        shell: pwsh
        run: |
          $dllPath = 'C:\Windows\SysWOW64\msoledbsql.dll'
          if (Test-Path $dllPath) {
            $version = (Get-Item $dllPath).VersionInfo.FileVersion
            echo "msoledbsql.dll version: $version"
            echo "## msoledbsql.dll Version: $version" >> $env:GITHUB_STEP_SUMMARY
          } else {
            echo "msoledbsql.dll not found at $dllPath."
            echo "## msoledbsql.dll not found at $dllPath" >> $env:GITHUB_STEP_SUMMARY
          }
